AllCops:
  Rails: true
  Include:
    - Rakefile
    - config.ru
  Exclude:
    - db/schema.rb
    - repos/**/*


# We right self-documenting code, right? Disabling for now.
Style/Documentation:
  Enabled: false

# Tests don't have to be awfully readable
Metrics/LineLength:
  Exclude:
    - spec/**/*

Metrics/AbcSize:
  Enabled: false
Metrics/MethodLength:
  Max: 20
Metrics/CyclomaticComplexity:
  Enabled: false
